namespace CodexTracker.App;

internal static partial class EnglishApp
{
    internal static readonly (string French, string English)[] Dashboard =
    [
        ("Comptes", "Accounts"),
        ("Changez de compte dans Codex ou Claude Code : le tracker suit automatiquement. Glissez son icône dans la barre d’état pour la garder visible.", "Switch accounts in Codex or Claude Code and the tracker follows automatically. Drag its icon into the notification area to keep it visible."),
        ("Compris", "Got it"),
        ("5 heures", "5 hours"),
        ("Reset semaine", "Weekly reset"),
        ("Resets en réserve", "Reset credits"),
        ("Modifier…", "Edit…"),
        ("Voir", "View"),
        ("Voir le compte probablement rechargé", "View the account that was probably refilled"),
        ("Consulter ce relevé avant de changer de compte dans Codex", "Check this reading before switching accounts in Codex"),
        ("Reset Codex…", "Codex reset…"),
        ("Déclarer un reset de tous les comptes Codex", "Declare a reset for all Codex accounts"),
        ("Actualiser et détecter les comptes Codex et Claude Code", "Refresh and detect Codex and Claude Code accounts"),
        ("Actualiser les quotas", "Refresh quotas"),
        ("Ouvrez Codex ou Claude Code pour commencer.", "Open Codex or Claude Code to get started."),
        ("Le compte connecté apparaîtra ici automatiquement.", "The signed-in account will appear here automatically."),
        ("Détecter maintenant", "Detect now"),
        ("Semaine", "Week"),
        ("Resets", "Resets"),
        ("Resets disponibles en réserve : survolez le nombre pour voir les dates", "Available reset credits: hover over the number to see the dates"),
        ("Prochain reset", "Next reset"),
        ("Compte actif", "Active account"),
        ("Changer le nom ou l’avatar", "Change the name or avatar"),
        ("Personnaliser l’avatar du compte", "Change the account avatar"),
        ("estimé", "estimated"),
        ("Détails et historique", "Details and history"),
        ("Détails et historique du compte", "Account details and history"),
        ("Réglages", "Settings"),
        ("Masquer dans la barre d’état — le suivi reste actif", "Hide to the notification area — tracking continues"),
        ("Masquer dans la barre d’état", "Hide to the notification area"),
        ("Réduire dans la barre des tâches", "Minimize to the taskbar"),
        ("Mettre à jour et relancer", "Update and restart"),
        ("Installer la mise à jour téléchargée et relancer Codex Tracker", "Install the downloaded update and restart Codex Tracker"),
        ("Vérifier", "Review"),
        ("Vérifier les données et les rappels dans les réglages", "Review data and reminders in settings"),
        ("Des données locales ou des rappels nécessitent votre attention.", "Local data or reminders need your attention."),
        ("Démo · comptes fictifs", "Demo · sample accounts"),
        ("Version installée de Codex Tracker", "Installed version of Codex Tracker"),
        ("Version installée : {0}", "Installed version: {0}"),
        ("Page inconnue.", "Unknown page."),
        ("Une mise à jour se télécharge…", "Downloading an update…"),
        ("Version {0} prête à installer", "Version {0} ready to install"),
        ("Le suivi continue en arrière-plan.", "Tracking continues in the background."),
        ("Maintenant, ou automatiquement au prochain démarrage du tracker.", "Now, or automatically the next time the tracker starts."),
        ("Téléchargée et vérifiée. Vos comptes et réglages sont conservés.", "Downloaded and verified. Your accounts and settings are kept."),
        ("Installation précédente interrompue. Vous pouvez réessayer.", "The previous installation was interrupted. You can try again."),
        ("Installation…", "Installing…"),
        ("Mise à jour indisponible", "Update unavailable"),
        ("La mise à jour n’est plus prête. Recherchez-la à nouveau dans les réglages.", "The update is no longer ready. Check for it again in settings."),
        ("Actualisation indisponible", "Refresh unavailable"),
        ("L’action n’a pas abouti", "The action did not complete"),
        ("Fermer", "Close"),
        ("Les captures de détails nécessitent le mode démonstration.", "Details screenshots require demo mode."),
        ("Les captures des réglages nécessitent le mode démonstration.", "Settings screenshots require demo mode."),
        ("Indisponible", "Unavailable"),
        ("Date non communiquée", "Date not provided"),
        ("Reset attendu", "Reset due"),
        ("Dans {0}", "In {0}"),
        ("{0} j {1:00} h", "{0}d {1:00}h"),
        ("{0} h {1:00} min", "{0}h {1:00}m"),
        ("{0} min {1:00} s", "{0}m {1:00}s"),
        ("Fenêtre inconnue", "Unknown window"),
        ("{0:0.#} jours", "{0:0.#} days"),
        ("{0:0.#} heures", "{0:0.#} hours"),
        ("{0} min", "{0} min"),
        ("à l’instant", "just now"),
        ("il y a {0} min", "{0} min ago"),
        ("il y a {0} h", "{0}h ago"),
        ("il y a {0} j", "{0}d ago"),
        ("[compte masqué]", "[hidden account]"),
        ("1 reset en réserve", "1 reset credit"),
        ("{0} resets en réserve", "{0} reset credits"),
        ("Réserve indisponible", "Reset credits unavailable"),
        ("Expiration passée {0}", "Expired {0}"),
        ("Expire le {0}", "Expires {0}"),
        ("Reçu le {0} · {1}", "Received {0} · {1}"),
        ("Expiration non communiquée", "Expiry not provided"),
        ("Aucune expiration communiquée par Codex.", "No expiry provided by Codex."),
        ("Dernier relevé : {0}\n{1}\nDisponibilité au moment de ce relevé.", "Last reading: {0}\n{1}\nAvailability at the time of this reading."),
        ("Épuisé dans", "Empty in"),
        ("À ce rythme", "At this pace"),
        ("jusqu’au reset", "until reset"),
        ("Épuisement estimé : {0}\n{1}", "Estimated to run out: {0}\n{1}"),
        ("restant · déclaré", "left · declared"),
        ("restant", "left"),
        ("Reset Codex déclaré pour le {0} · {1}.\n100 % déclaré, sous réserve d’une utilisation depuis le reset.\nDernier quota mesuré : {2} le {3}.\nLes prochains relevés mesurés sont prioritaires.", "Codex reset declared for {0} · {1}.\n100% declared, unless the account was used since the reset.\nLast measured quota: {2} on {3}.\nNew measured readings take priority."),
        ("1 compte", "1 account"),
        ("{0} comptes", "{0} accounts"),
        ("Équipe", "Team"),
        ("Entreprise", "Enterprise"),
        ("Offre inconnue", "Unknown plan"),
        ("À détecter", "Not detected yet"),
        ("à vérifier", "to check"),
        ("actif", "active"),
        ("à détecter", "not detected yet"),
        ("Compte actif dans {0}{1}", "Active account in {0}{1}"),
        ("{0}{1} · dernier relevé disponible", "{0}{1} · last available reading"),
        ("Reset Codex déclaré", "Codex reset declared"),
        ("Semaine + 5 h probablement à 100 %", "Week + 5h probably at 100%"),
        ("Semaine probablement à 100 %", "Week probably at 100%"),
        ("5 h probablement à 100 %", "5h probably at 100%"),
        ("Reset général annoncé comme terminé le {0} · {1}.\nSource : {2}\nPortée : {3}\nEstimation valable jusqu’au {4}.", "General reset announced as completed on {0} · {1}.\nSource: {2}\nScope: {3}\nEstimate valid until {4}."),
        ("{0} prévu le {1} · {2}.", "{0} scheduled for {1} · {2}."),
        ("Dernier quota mesuré : {0} le {1}.\nProbablement revenu à 100 % si le compte n’a pas été utilisé ailleurs. Ouvrez ce compte dans {2} pour confirmer.", "Last measured quota: {0} on {1}.\nProbably back to 100% if the account was not used elsewhere. Open this account in {2} to confirm."),
        ("Dernier quota mesuré : {0}\nRelevé : {1}", "Last measured quota: {0}\nReading: {1}"),
        ("déclaré", "declared"),
        ("semaine", "week"),
        ("5 h : {0} · déclaré", "5h: {0} · declared"),
        ("5 h : {0}", "5h: {0}"),
        ("À reconfirmer", "To reconfirm"),
        ("Reset passé", "Reset passed"),
        ("Reset hebdomadaire {0}", "Weekly reset {0}"),
        ("Pas de resets en réserve", "No reset credits"),
        ("Claude Code ne communique pas de resets en réserve.", "Claude Code does not report reset credits."),
        ("Période indisponible", "Period unavailable"),
        ("début inconnu", "unknown start"),
        ("fin inconnue", "unknown end"),
        ("Période d’abonnement active\nDébut : {0}\n{1}\nFin : {2}\n{3}", "Active subscription period\nStart: {0}\n{1}\nEnd: {2}\n{3}"),
        ("Actualisation en cours…", "Refreshing…"),
        ("Ouvrez ce compte dans {0} pour détecter ses quotas.", "Open this account in {0} to detect its quotas."),
        ("Mis à jour {0}", "Updated {0}"),
        ("Dernier relevé {0} · quota figé tant que ce compte est inactif", "Last reading {0} · quota frozen while this account is inactive"),
        ("Offre : {0}", "Plan: {0}"),
        ("{0} : {1} restant\nReset : {2}\n{3} · {4}", "{0}: {1} left\nReset: {2}\n{3} · {4}"),
        ("Reset Codex déclaré le {0} · {1} compte(s) en attente d’un nouveau relevé", "Codex reset declared on {0} · {1} account(s) awaiting a new reading"),
        ("Reset général annoncé · estimation datée et sources dans Resets", "General reset announced · dated estimate and sources in Resets"),
        ("Reset prévu passé · estimation à confirmer dans le compte concerné", "Scheduled reset passed · estimate to confirm in the account"),
        ("Un autre compte est probablement rechargé", "Another account was probably refilled"),
        ("{0} autres comptes sont probablement rechargés", "{0} other accounts were probably refilled"),
        ("Première actualisation…", "First refresh…"),
        ("En attente du compte actif", "Waiting for the active account"),
        ("Aucun relevé reçu", "No reading received"),
        ("Dernière mise à jour : {0}", "Last updated: {0}"),
        ("{0} · actualisation…", "{0} · refreshing…"),
        ("{0} · échec de lecture des quotas", "{0} · failed to read quotas"),
        ("Ouvrez votre compte dans Codex ou Claude Code.", "Open your account in Codex or Claude Code."),
        ("{0} · dernier relevé reçu : {1}\n{2}\n{3}", "{0} · last reading received: {1}\n{2}\n{3}"),
        ("À vérifier dans Codex : {0}", "Check in Codex: {0}"),
        ("Relevé {0} · quota actuel à confirmer", "Read {0} · current quota to confirm"),
        ("Relevé : {0}\n{1}", "Reading: {0}\n{1}"),
        ("Aperçu Codex Tracker", "Codex Tracker preview"),
        ("Ouvrir le suivi", "Open tracker"),
        ("En attente d’un compte", "Waiting for an account"),
        ("Compte actif dans {0}", "Active account in {0}"),
        ("Compte affiché dans l’icône", "Account shown in the icon"),
        ("Prochain reset à reconfirmer", "Next reset to reconfirm"),
        ("Reset hebdomadaire indisponible", "Weekly reset unavailable"),
        ("Reset Codex déclaré le {0} · {1}", "Codex reset declared on {0} · {1}"),
        ("Dates d’expiration non communiquées", "Expiry dates not provided"),
        ("Ouvrez Codex ou Claude Code pour détecter votre compte.", "Open Codex or Claude Code to detect your account."),
        ("le {0:dd/MM à HH:mm}", "on {0:dd/MM} at {0:HH:mm}"),
        ("Dernier relevé {0}", "Last reading {0}"),
        ("Données anciennes · {0}", "Stale data · {0}"),
        ("Actualisé {0}", "Refreshed {0}"),
    ];
}
