namespace CodexTracker.App;

internal static partial class EnglishApp
{
    internal static readonly (string French, string English)[] Shell =
    [
        ("Codex Tracker · en attente d’un compte", "Codex Tracker · waiting for an account"),
        ("indisponible", "unavailable"),
        ("{0}% restant", "{0}% left"),
        ("{0} · reset attendu", "{0} · reset due"),
        ("{0} · reset dans {1}", "{0} · resets in {1}"),
        ("{0} · déclaré", "{0} · declared"),
        ("{0} · dernier relevé", "{0} · last reading"),
        ("{0} · données anciennes", "{0} · stale data"),
        ("{0} · {1}\nSemaine : {2}\nReset : {3}", "{0} · {1}\nWeek: {2}\nReset: {3}"),
        ("Actualiser", "Refresh"),
        ("Quitter", "Quit"),
        ("Action impossible", "Action failed"),
        ("1 autre événement dans le suivi.", "1 more event in the tracker."),
        ("{0} autre événement dans le suivi.", "{0} more events in the tracker."),
        ("Aucun rappel à transmettre à Windows.", "No reminder to send to Windows."),
        ("Les alertes de quota et de reset apparaîtront ici. Cliquez pour ouvrir l’onglet Resets.", "Quota and reset alerts will appear here. Click to open the Resets tab."),
        ("Compte suivi", "Tracked account"),
        ("Quota bientôt épuisé à ce rythme", "Quota running out at this pace"),
        ("{0} · {1}\nAu rythme actuel, plus rien vers {2:HH:mm}, avant la recharge.", "{0} · {1}\nAt the current pace, nothing left by {2:HH:mm}, before the refill."),
        ("Quota rechargé", "Quota refilled"),
        ("{0} · {1}\n{2} a confirmé le renouvellement du quota.", "{0} · {1}\n{2} confirmed that the quota was renewed."),
        ("Quota bientôt épuisé", "Quota running low"),
        ("{0} · {1}\nIl reste {2} % ou moins. Cliquez pour consulter le suivi.", "{0} · {1}\n{2}% or less left. Click to open the tracker."),
        ("L’icône de notification est indisponible. Rouvrez le tracker puis réessayez.", "The notification icon is unavailable. Reopen the tracker and try again."),
        ("Les notifications Windows sont désactivées. Vérifiez les paramètres de notification Windows puis réessayez.", "Windows notifications are turned off. Check the Windows notification settings and try again."),
        ("Windows indique une session verrouillée ou inactive.", "Windows reports a locked or inactive session."),
        ("Windows suspend les notifications : une application est en plein écran ou le mode présentation est actif.", "Windows is holding notifications: an app is full screen or presentation mode is on."),
        ("Windows suspend les notifications pendant une application en plein écran exclusif.", "Windows holds notifications while an app runs in exclusive full screen."),
        ("Le mode présentation de Windows suspend les notifications.", "Windows presentation mode holds notifications."),
        ("Windows suspend temporairement les notifications après une ouverture de session ou une mise à niveau.", "Windows temporarily holds notifications after a sign-in or an upgrade."),
        ("{0} Le rappel sera réessayé tant qu’il reste pertinent.", "{0} The reminder will be retried while it remains relevant."),
        ("{0} Quittez ce mode puis réessayez.", "{0} Leave this mode and try again."),
        ("Demande transmise à Windows ; affichage non confirmé. Si rien n’apparaît, vérifiez « Ne pas déranger » et les paramètres de notification Windows.", "Request sent to Windows; display not confirmed. If nothing appears, check “Do not disturb” and the Windows notification settings."),
        ("Windows n’a pas pu recevoir la notification. Rouvrez le tracker puis réessayez.", "Windows could not receive the notification. Reopen the tracker and try again."),
        ("Dans 15 minutes", "In 15 minutes"),
        ("Dans 1 heure", "In 1 hour"),
        ("Dans 4 heures", "In 4 hours"),
        ("Rappeler", "Snooze"),
        ("Le canal de notification Windows n’est pas disponible. Rouvrez le tracker puis réessayez.", "The Windows notification channel is unavailable. Reopen the tracker and try again."),
        ("Le journal des rappels est illisible. Les envois sont suspendus pour éviter les doublons.", "The reminder log is unreadable. Sending is paused to avoid duplicates."),
        ("Tests d’envoi désactivés dans la démonstration.", "Send tests are disabled in the demo."),
        ("Le moteur de rappels est indisponible.", "The reminder engine is unavailable."),
        ("Le tracker est suspendu ou en cours de fermeture. Réessayez après sa reprise.", "The tracker is suspended or closing. Try again once it resumes."),
        ("Les aperçus nécessitent --demo.", "Previews require --demo."),
        ("MCP indisponible : journal local illisible. Le suivi reste actif.", "MCP unavailable: local log unreadable. Tracking continues."),
        ("{0} nécessite --demo.", "{0} requires --demo."),
        ("Codex Tracker n’a pas pu démarrer.\n\n{0}", "Codex Tracker could not start.\n\n{0}"),
        ("DPI : 96, 120, 144 ou 192.", "DPI: 96, 120, 144 or 192."),
        ("Reprise du suivi", "Resuming tracking"),
        ("Windows redirige encore le stockage. Lancez Codex Tracker depuis le menu Démarrer ; aucun compte n’a été réinitialisé.", "Windows is still redirecting storage. Start Codex Tracker from the Start menu; no account has been reset."),
        ("Impossible d’ouvrir le stockage habituel.\n\n{0}", "Cannot open the usual storage.\n\n{0}"),
        ("Choisissez une image enregistrée sur ce PC.", "Choose an image saved on this PC."),
        ("Choisissez une image de moins de 8 Mo.", "Choose an image smaller than 8 MB."),
        ("Choisissez un PNG ou JPEG.", "Choose a PNG or JPEG."),
        ("Image trop grande (40 mégapixels maximum).", "Image too large (40 megapixels maximum)."),
        ("Dimensions de l’image non prises en charge.", "Unsupported image dimensions."),
        ("Le texte de l’icône n’a pas pu être rendu.", "The icon text could not be rendered."),
        ("Le texte de l’icône dépasse la taille disponible.", "The icon text does not fit the available size."),
        ("Crédit de reset", "Reset credit"),
        ("Source fictive", "Sample source"),
        ("Au rythme récent, estimation indicative fondée sur les relevés de démonstration. Votre usage peut changer.", "At the recent pace: an indicative estimate based on demo readings. Your usage may change."),
        ("Ouvrez ce compte dans Codex pour obtenir une estimation fondée sur son utilisation récente.", "Open this account in Codex to get an estimate based on its recent usage."),
    ];
}
