namespace CodexTracker.App;

internal static partial class EnglishApp
{
    internal static readonly (string French, string English)[] Resets =
    [
        // ResetsView: heading, actions and filters
        ("Prochains resets", "Upcoming resets"),
        ("Reset Codex…", "Codex reset…"),
        ("Déclarer ou modifier l’heure d’un reset général Codex", "Declare or change the time of a global Codex reset"),
        ("Actualiser les comptes actifs de Codex et Claude Code", "Refresh the active Codex and Claude Code accounts"),
        ("Actualiser les comptes actifs", "Refresh active accounts"),
        ("Autres actions", "More actions"),
        ("Autres actions des resets", "More reset actions"),
        ("Google Agenda ↗", "Google Calendar ↗"),
        ("Filtrer les resets par compte", "Filter resets by account"),
        ("Filtrer les resets par type", "Filter resets by type"),
        ("Tous les comptes", "All accounts"),
        ("Tous les types", "All types"),
        ("Hebdomadaires", "Weekly"),
        ("5 heures", "5 hours"),
        ("Réserves", "Reset credits"),
        ("Liste", "List"),
        ("Semaine", "Week"),
        ("Vue liste des resets", "Reset list view"),
        ("Vue semaine des resets", "Reset week view"),

        // ResetsView: entries
        ("Réserves sans date", "Undated reset credits"),
        ("Reset hebdomadaire", "Weekly reset"),
        ("Reset 5 heures", "5-hour reset"),
        ("Expiration de réserve", "Credit expiry"),
        ("Détectez un compte pour retrouver ses prochaines échéances.", "Detect an account to see its upcoming resets."),
        ("1 échéance à venir", "1 upcoming reset"),
        ("{0} échéances à venir", "{0} upcoming resets"),
        ("Selon les derniers relevés. Les comptes inactifs ne sont pas actualisés en arrière-plan.", "Based on the latest readings. Inactive accounts are not refreshed in the background."),
        ("Reset Codex déclaré · {0:dd/MM à HH:mm}", "Codex reset declared · {0:dd/MM 'at' HH:mm}"),
        ("Les prochaines échéances seront confirmées par de nouveaux relevés.", "Upcoming resets will be confirmed by new readings."),
        ("Aucun compte détecté.", "No account detected."),
        ("Aucune date à venir connue pour cette sélection.", "No known upcoming dates for this selection."),
        ("À confirmer · {0}", "To confirm · {0}"),
        ("Dates inconnues · {0}", "Unknown dates · {0}"),
        ("Reset général annoncé · voir les sources", "Global reset announced · see sources"),
        ("Réserves Codex · non communiquées", "Codex reset credits · not reported"),
        ("Réserves Codex · {0} resets au dernier relevé", "Codex reset credits · {0} at last reading"),
        ("compteurs incomplets", "incomplete counts"),
        ("À utiliser en priorité : {0} · {1}", "Use first: {0} · {1}"),
        ("Aucune réserve à afficher pour cette sélection.", "No reset credits to show for this selection."),
        ("Compteurs serveur au dernier relevé. Les dates d’expiration ne permettent pas de déduire le nombre de resets disponibles.", "Server counts at the last reading. Expiry dates do not tell how many resets are available."),
        ("Aujourd’hui", "Today"),
        ("Demain", "Tomorrow"),
        ("Date non communiquée", "Date not provided"),
        ("Date non communiquée par {0}", "Date not provided by {0}"),
        ("Relevé : {0}", "Reading: {0}"),
        ("Date indisponible", "Date unavailable"),
        ("Reçu le {0} · {1}", "Received {0} · {1}"),
        ("{0} · {1} · détails", "{0} · {1} · details"),
        ("≈100 % · à confirmer", "≈100% · to confirm"),
        ("Date inconnue", "Date unknown"),
        ("Expiration passée", "Expired"),
        ("Reset à confirmer dans {0}", "Reset to confirm in {0}"),
        ("Quota probablement rechargé. Ouvrez le compte pour confirmer ; le dernier relevé reste conservé.", "Quota probably refilled. Open the account to confirm; the last reading is kept."),
        ("Dernier essai en échec · relevé conservé", "Last attempt failed · reading kept"),
        ("Actif · relevé {0}", "Active · read {0}"),
        ("relevé {0}", "Read {0}"),
        ("Aucun relevé", "No reading"),
        ("Dernier relevé : {0}", "Last reading: {0}"),

        // ResetsView: week
        ("Semaine précédente", "Previous week"),
        ("Semaine actuelle", "Current week"),
        ("Semaine suivante", "Next week"),
        ("Cette semaine", "This week"),
        ("1 reset", "1 reset"),
        ("{0} resets", "{0} resets"),
        ("Échéances du {0:dd/MM/yyyy}, {1} resets", "Resets on {0:dd/MM/yyyy}: {1}"),
        ("1 échéance cette semaine", "1 reset this week"),
        ("{0} échéances cette semaine", "{0} resets this week"),
        ("1 échéance ce jour", "1 reset on this day"),
        ("{0} échéances ce jour", "{0} resets on this day"),
        ("Aucune échéance connue cette semaine.", "No known resets this week."),
        ("Aucune échéance connue ce jour.", "No known resets on this day."),

        // GlobalResetCard
        ("Reset général · annoncé comme terminé", "Global reset · announced as done"),
        ("Tous les abonnements", "All plans"),
        ("Abonnements payants concernés", "Paid plans affected"),
        ("semaine", "weekly"),
        ("Le reset déclaré manuellement est prioritaire pour les comptes concernés.", "The manually declared reset takes priority for the affected accounts."),
        ("Les quotas mesurés restent prioritaires · aucune estimation pour cette sélection.", "Measured quotas take priority · no estimate for this selection."),
        ("1 compte probablement rechargé · ≈100 % à confirmer", "1 account probably refilled · ≈100% to confirm"),
        ("{0} comptes probablement rechargés · ≈100 % à confirmer", "{0} accounts probably refilled · ≈100% to confirm"),
        ("100 % déclaré · reset manuel prioritaire", "100% declared · manual reset takes priority"),
        ("Seuls les relevés antérieurs à l’annonce initiale du {0} permettent une estimation.", "Only readings taken before the initial announcement on {0} allow an estimate."),
        ("Détail des comptes ({0})", "Account details ({0})"),
        ("Les dates ci-dessous restent celles des anciens relevés ; aucune nouvelle échéance n’est inventée.", "The dates below still come from earlier readings; no new reset time is made up."),
        ("Voir la confirmation ↗", "See confirmation ↗"),
        ("Voir la portée ↗", "See scope ↗"),
        ("Impossible d’ouvrir le navigateur. {0}", "Couldn’t open the browser. {0}"),
        ("Sources vérifiées le {0}. Les nouveaux relevés et les déclarations manuelles restent prioritaires.", "Sources checked on {0}. New readings and manual declarations still take priority."),
        ("Estimation expirée · ouvrir les comptes dans Codex pour vérifier.", "Estimate expired · open the accounts in Codex to check."),
        ("Estimation valable encore {0}", "Estimate valid for another {0}"),
        ("Fin de validité : {0}", "Valid until: {0}"),
        ("L’estimation est retirée plus tôt dès qu’un nouveau relevé est reçu.", "The estimate is removed earlier as soon as a new reading arrives."),
        ("{0} j {1:00} h", "{0} d {1:00} h"),
        ("{0} h {1:00} min", "{0} h {1:00} min"),
        ("{0} min {1:00} s", "{0} min {1:00} s"),
        ("≈100 % estimé · à confirmer dans Codex", "≈100% estimated · confirm in Codex"),
        ("Compte actif · quota mesuré conservé", "Active account · measured quota kept"),
        ("Relevé plus récent · quota mesuré conservé", "Newer reading · measured quota kept"),
        ("Hors de la portée annoncée", "Outside the announced scope"),
        ("Relevé trop ancien pour estimer", "Reading too old to estimate"),
        ("Période d’abonnement à reconfirmer", "Subscription period to reconfirm"),
        ("Estimation expirée", "Estimate expired"),
        ("Données insuffisantes pour estimer", "Not enough data to estimate"),
    ];
}
