namespace CodexTracker.App;

internal static partial class EnglishApp
{
    internal static readonly (string French, string English)[] Windows =
    [
        // Shared buttons of secondary windows
        ("Fermer", "Close"),
        ("Annuler", "Cancel"),
        ("Enregistrer", "Save"),

        // HistoryWindow ("Semaine" and "5 heures" are in Resets)
        ("Détails et historique", "Details and history"),
        ("Resets en réserve", "Reset credits"),
        ("Quota restant", "Quota left"),
        ("24 heures", "24 hours"),
        ("7 jours", "7 days"),
        ("Estimation prudente", "Cautious estimate"),
        ("Nom et avatar…", "Name and avatar…"),
        ("Exporter les échéances…", "Export reset dates…"),
        ("Dates exactes et détails", "Exact dates and details"),
        ("Retirer du suivi", "Stop tracking"),
        ("Période d’abonnement : {0}", "Subscription period: {0}"),
        ("Épuisement estimé : {0}", "Estimated run-out: {0}"),
        ("Échéance estimée atteinte · à réévaluer", "Estimated run-out reached · to reassess"),
        ("Fenêtre 5 h", "5-hour window"),
        ("Quota hebdomadaire", "Weekly quota"),
        ("Pas d’estimation fiable pour le moment", "No reliable estimate yet"),
        ("reset attendu", "reset expected"),
        ("dans {0}", "in {0}"),
        ("Aucun relevé sur cette période. L’historique se construit quand le compte est actif.", "No readings in this period. History builds up while the account is active."),
        ("{0} relevés · les interruptions et les resets restent visibles dans la courbe.", "Readings: {0} · gaps and resets stay visible in the chart."),
        ("Retirer ce compte du suivi ?", "Stop tracking this account?"),
        ("Son historique local sera supprimé. Il réapparaîtra quand vous l’ouvrirez dans son application.", "Its local history will be deleted. It will reappear when you open it in its app."),
        ("Retirer", "Remove"),
        ("Action indisponible", "Action unavailable"),
        ("Maintenant", "Now"),
        ("Les premiers relevés apparaîtront ici.", "The first readings will appear here."),

        // CalendarWindow
        ("Calendrier", "Calendar"),
        ("Google Agenda", "Google Calendar"),
        ("Toutes vos échéances", "All your reset dates"),
        ("Resets et expirations, dans l’agenda de votre choix.", "Resets and expiries, in the calendar of your choice."),
        ("Importer dans Google Agenda", "Import into Google Calendar"),
        ("Utilise votre navigateur habituel. Si Google demande une connexion, connectez-vous puis cliquez à nouveau ici.", "Uses your usual browser. If Google asks you to sign in, sign in and click here again."),
        ("Google Agenda est ouvert. Sélectionnez le fichier préparé puis validez l’import.", "Google Calendar is open. Select the prepared file, then confirm the import."),
        ("Impossible de préparer le fichier. Essayez l’export vers un autre emplacement.", "Couldn’t prepare the file. Try exporting to another location."),
        ("Le fichier est préparé ici ; vous confirmez l’import dans Google Agenda.", "The file is prepared here; you confirm the import in Google Calendar."),
        ("1. Dans Google, cliquez sur « Sélectionner un fichier » et collez ce chemin.\n2. Choisissez votre agenda, puis cliquez sur « Importer ».", "1. In Google, click “Select file from your computer” and paste this path.\n2. Choose your calendar, then click “Import”."),
        ("Chemin du fichier à importer", "Path of the file to import"),
        ("Copier le chemin", "Copy path"),
        ("Chemin copié. Collez-le dans le sélecteur de fichier de Google Agenda.", "Path copied. Paste it into the Google Calendar file picker."),
        ("Sélectionnez le chemin ci-dessus et copiez-le avec Ctrl+C.", "Select the path above and copy it with Ctrl+C."),
        ("Ouvrir Google Agenda ↗", "Open Google Calendar ↗"),
        ("Terminez l’import dans Google Agenda.", "Finish the import in Google Calendar."),
        ("Ouvre un événement prérempli. Vérifiez-le, puis cliquez sur Enregistrer dans Google Agenda.", "Opens a prefilled event. Check it, then click Save in Google Calendar."),
        ("Ajouter une seule échéance", "Add a single reset date"),
        ("Exporter un fichier .ics…", "Export an .ics file…"),
        ("Pour Google Agenda, Outlook, Apple Calendar ou une sauvegarde locale", "For Google Calendar, Outlook, Apple Calendar or a local backup"),
        ("Ajout ponctuel, sans synchronisation. Évitez d’ajouter la même échéance plusieurs fois.", "One-off addition, no sync. Avoid adding the same date more than once."),
        ("Aucune échéance future disponible. Actualisez le compte dans Codex ou Claude Code.", "No upcoming dates available. Refresh the account in Codex or Claude Code."),
        ("{0} échéances connues · prochaine le {1}", "Known dates: {0} · next on {1}"),
        ("Ajouter ↗", "Add ↗"),
        ("Préremplir cet événement dans Google Agenda", "Prefill this event in Google Calendar"),
        ("Cette échéance a changé. Choisissez sa nouvelle date dans la liste.", "This date has changed. Pick its new date from the list."),
        ("Événement prérempli ouvert. Cliquez sur Enregistrer dans Google Agenda pour l’ajouter.", "Prefilled event opened. Click Save in Google Calendar to add it."),
        ("Le navigateur n’a pas pu s’ouvrir. Réessayez ou utilisez le fichier .ics.", "The browser couldn’t open. Try again or use the .ics file."),
        ("Calendrier iCalendar", "iCalendar file"),
        ("Le fichier n’a pas pu être enregistré. Choisissez un autre emplacement.", "The file couldn’t be saved. Choose another location."),
        ("Fichier prêt · {0} échéances · {1:HH:mm:ss}", "File ready · dates: {0} · {1:HH:mm:ss}"),
        ("Fichier prêt à importer. Aucun ajout dans Google Agenda n’est confirmé par le tracker.", "File ready to import. The tracker cannot confirm anything was added to Google Calendar."),

        // ManualCodexResetWindow
        ("Déclarer un reset Codex", "Declare a Codex reset"),
        ("À quelle heure le reset général a-t-il eu lieu ?", "When did the global reset happen?"),
        ("Tous les comptes Codex sans relevé plus récent afficheront 100 % sur les quotas de 5 heures et de la semaine, avec la mention « reset déclaré ». Les comptes Claude Code et les resets en réserve sont conservés.", "All Codex accounts without a newer reading will show 100% on the 5-hour and weekly quotas, marked “reset declared”. Claude Code accounts and reset credits are kept."),
        ("Date", "Date"),
        ("Date du reset Codex", "Codex reset date"),
        ("Heure (HH:mm)", "Time (HH:mm)"),
        ("Heure du reset Codex", "Codex reset time"),
        ("Heure locale · {0}", "Local time · {0}"),
        ("Les derniers relevés et l’historique mesuré restent conservés. Un nouveau relevé remplace la déclaration pour son compte. Les prochaines échéances restent inconnues jusqu’à ce relevé ; la déclaration expire après 5 h / 7 jours.", "The latest readings and measured history are kept. A new reading replaces the declaration for its account. Upcoming resets stay unknown until that reading; the declaration expires after 5 h / 7 days."),
        ("Annuler la déclaration", "Withdraw declaration"),
        ("Déclarer le reset", "Declare reset"),
        ("Indiquez une date et une heure au format HH:mm.", "Enter a date and a time in HH:mm format."),
        ("Cette heure tombe dans un changement d’heure. Choisissez une heure locale sans ambiguïté.", "This time falls during a clock change. Choose an unambiguous local time."),
        ("Le reset doit avoir eu lieu : cette heure est dans le futur.", "The reset must already have happened: this time is in the future."),
        ("Les réglages ont changé. Fermez puis rouvrez ce formulaire avant de déclarer le reset.", "Settings have changed. Close and reopen this form before declaring the reset."),
        ("La déclaration n’a pas pu être enregistrée. Réessayez.", "The declaration couldn’t be saved. Try again."),

        // AccountAppearanceWindow
        ("Personnaliser le compte", "Customize account"),
        ("Compte", "Account"),
        ("Changer la photo", "Change photo"),
        ("Changer la photo du compte", "Change account photo"),
        ("Choisir une photo…", "Choose a photo…"),
        ("Utiliser les initiales", "Use initials"),
        ("Image locale, recadrée au centre. PNG ou JPEG, 8 Mo maximum.", "Local image, center-cropped. PNG or JPEG, 8 MB max."),
        ("Nom affiché", "Display name"),
        ("Laissez vide pour afficher l’adresse. L’identité de connexion reste inchangée.", "Leave empty to show the email address. The sign-in identity stays unchanged."),
        ("Photo du compte", "Account photo"),
        ("Impossible de lire cette image. Choisissez un PNG ou JPEG local de moins de 8 Mo.", "Couldn’t read this image. Choose a local PNG or JPEG under 8 MB."),
        ("La personnalisation n’a pas pu être enregistrée.", "The customization couldn’t be saved."),
        ("Personnalisation", "Customization"),
    ];
}
