namespace CodexTracker.App;

internal static partial class EnglishApp
{
    internal static readonly (string French, string English)[] Settings =
    [
        // SettingsView · Général
        ("Général", "General"),
        ("Adaptez le suivi à votre façon de travailler.", "Tailor the tracker to the way you work."),
        ("Apparence", "Appearance"),
        ("Comme Windows", "Match Windows"),
        ("Clair", "Light"),
        ("Sombre", "Dark"),
        ("Thème", "Theme"),
        ("Langue", "Language"),
        ("Appliquée au prochain démarrage du tracker.", "Applied the next time the tracker starts."),
        ("Redémarrer maintenant", "Restart now"),
        ("Aperçu au survol de l’icône", "Preview on icon hover"),
        ("Le quota et le prochain reset, sans ouvrir le panneau.", "Quota and next reset, without opening the panel."),
        ("Actualisation", "Refresh"),
        ("Compte actif", "Active account"),
        ("Chaque minute", "Every minute"),
        ("Toutes les 2 min", "Every 2 min"),
        ("Toutes les 5 min", "Every 5 min"),
        ("Adapter à mon activité", "Adapt to my activity"),
        ("Passe à 10 min après 5 min sans clavier ni souris. Reprend la fréquence choisie à votre retour. La détection des comptes reste immédiate.",
            "Switches to 10 min after 5 min without keyboard or mouse input. Returns to your chosen frequency when you’re back. Account detection stays immediate."),
        ("L’application Claude fournit automatiquement ses derniers quotas locaux, sans configuration. Les comptes personnels et d’entreprise sont séparés, même sur la même adresse. Pour les relevés du terminal, ajoutez le réglage ci-dessous puis ouvrez une nouvelle session.",
            "The Claude app provides its latest local quotas automatically, with no setup. Personal and business accounts are kept separate, even on the same address. For terminal readings, add the setting below, then open a new session."),
        ("Copier le réglage Claude Code", "Copy Claude Code setting"),
        ("Profil", "Profile"),
        ("Emportez vos comptes, leurs derniers relevés, l’historique, les réglages, noms et avatars sur un autre PC. Le fichier est chiffré par un mot de passe ; les clés des canaux et l’accès des assistants restent sur ce PC.", "Take your accounts, their latest readings, history, settings, names and avatars to another PC. The file is encrypted with a password; channel keys and assistant access stay on this PC."),
        ("Exporter le profil…", "Export profile…"),
        ("Importer un profil…", "Import a profile…"),
        ("Profil Codex Tracker", "Codex Tracker profile"),
        ("Protéger le profil", "Protect the profile"),
        ("Ce mot de passe sera demandé à l’import. Il n’est enregistré nulle part : sans lui, le fichier est illisible.", "This password is asked for on import. It is stored nowhere: without it, the file cannot be read."),
        ("Profil exporté", "Profile exported"),
        ("{0} comptes, leur historique et vos réglages sont dans le fichier chiffré. Importez-le depuis Réglages → Application sur l’autre PC.", "{0} accounts, their history and your settings are in the encrypted file. Import it from Settings → Application on the other PC."),
        ("Importer un profil", "Import a profile"),
        ("Saisissez le mot de passe choisi lors de l’export.", "Enter the password chosen when exporting."),
        ("Importer ce profil ?", "Import this profile?"),
        ("{0} comptes, exportés le {1:dd/MM/yyyy à HH:mm}.\nLes comptes et l’historique s’ajoutent à ceux de ce PC ; un relevé plus récent ici est conservé. Les réglages, rappels, noms et avatars du fichier remplacent ceux de ce PC. Les clés des canaux et l’accès des assistants ne changent pas.", "{0} accounts, exported on {1:dd/MM/yyyy 'at' HH:mm}.\nAccounts and history are added to this PC's; a newer reading here is kept. The file's settings, reminders, names and avatars replace this PC's. Channel keys and assistant access do not change."),
        ("Importer", "Import"),
        ("Profil importé", "Profile imported"),
        ("{0} comptes ajoutés, {1} mis à jour.", "{0} accounts added, {1} updated."),
        ("La langue du profil s’appliquera au prochain démarrage.", "The profile's language applies at the next start."),
        ("Continuer", "Continue"),
        ("Mot de passe", "Password"),
        ("Confirmer le mot de passe", "Confirm password"),
        ("Les deux mots de passe diffèrent.", "The two passwords differ."),
        ("Relevés du terminal actifs · dernier le {0}", "Terminal readings active · last on {0}"),
        ("Ancien : ouvrez une session Claude Code pour remettre à jour la date du reset.", "Old: open a Claude Code session to refresh the reset date."),
        ("Réglage détecté · en attente d’une session Claude Code.", "Setting found · waiting for a Claude Code session."),
        ("Relevés du terminal non configurés : la date du reset de la semaine reste estimée.", "Terminal readings not set up: the weekly reset date stays estimated."),
        ("Réglage copié", "Setting copied"),
        ("Le presse-papiers est indisponible. Réessayez.", "The clipboard is unavailable. Try again."),
        ("Dans ~/.claude/settings.json (ou CLAUDE_CONFIG_DIR) : fusionnez SessionStart avec vos hooks existants et ajoutez statusLine. Si vous avez déjà une barre de statut, conservez-la et appelez le collecteur depuis son script. Les quotas arrivent quand vous utilisez Claude Code ; les dates de relevé sont conservées.",
            "In ~/.claude/settings.json (or CLAUDE_CONFIG_DIR): merge SessionStart with your existing hooks and add statusLine. If you already have a status line, keep it and call the collector from its script. Quotas arrive as you use Claude Code; reading dates are kept."),

        // SettingsView · Rappels
        ("Rappels", "Reminders"),
        ("Choisissez les échéances, les comptes et les canaux utiles.", "Choose the due dates, accounts and channels you need."),
        ("Échéances", "Due dates"),
        ("Quotas", "Quotas"),
        ("Prévenir quand le quota restant franchit un seuil.", "Notify when the remaining quota crosses a threshold."),
        ("20 %", "20%"),
        ("10 %", "10%"),
        ("5 %", "5%"),
        ("Prévenir avant l’épuisement", "Notify before running out"),
        ("Si le rythme observé vide un quota avant sa recharge, une notification arrive environ une heure avant. Une fois par période, sans estimation si la consommation est irrégulière.",
            "If the observed pace would empty a quota before it refills, a notification arrives about an hour beforehand. Once per period, with no estimate when usage is irregular."),
        ("Prévenir après un reset", "Notify after a reset"),
        ("Notification Windows après confirmation par Codex, ou à l’échéance d’un compte inactif : quota probablement à 100 %, à confirmer. Reprise des échéances récentes après veille.",
            "Windows notification once Codex confirms it, or at an inactive account’s due date: quota probably at 100%, to confirm. Recent due dates are caught up after sleep."),
        ("Annonces de resets généraux", "Global reset announcements"),
        ("Vérifier les annonces publiques", "Check public announcements"),
        ("Toutes les 15 min : index communautaire shixilin.com, puis vérification des posts originaux via X. Aucune donnée de compte transmise. Certaines formulations restent indétectables.",
            "Every 15 min: the shixilin.com community index, then verification of the original posts via X. No account data is sent. Some wordings remain undetectable."),
        ("Les comptes inactifs concernés affichent ≈100 % pendant 24 h maximum (5 h pour le quota court). Le dernier relevé reste conservé. Les notifications suivent le réglage « Prévenir après un reset ».",
            "Affected inactive accounts show ≈100% for up to 24 h (5 h for the short quota). The last reading is kept. Notifications follow the “Notify after a reset” setting."),
        ("Vérifier les annonces", "Check announcements"),
        ("Vérification…", "Checking…"),
        ("Vérification désactivée.", "Checking is off."),
        ("Démonstration · aucun accès réseau.", "Demo · no network access."),
        ("Vérification des sources en cours…", "Checking sources…"),
        ("Dernier contrôle réussi : {0} · {1}", "Last successful check: {0} · {1}"),
        ("Aucun contrôle réussi pour le moment.", "No successful check yet."),
        ("Aucune annonce récente reconnue.", "No recent announcement detected."),
        ("Prochaine vérification imminente.", "Next check is imminent."),
        ("Prochain essai : {0}", "Next attempt: {0}"),
        ("Aucun accès réseau dans la démonstration.", "No network access in the demo."),
        ("Prochain contrôle manuel possible le {0}. Les limites de la source sont respectées.", "Next manual check possible on {0}. The source’s limits are respected."),
        ("Relit les annonces publiques sans actualiser les comptes. Un contrôle manuel par minute maximum.", "Rereads public announcements without refreshing accounts. At most one manual check per minute."),

        // SettingsView · other pages
        ("Canaux", "Channels"),
        ("Notifications Windows et connecteurs facultatifs.", "Windows notifications and optional connectors."),
        ("Historique", "History"),
        ("Le suivi local de vos rappels sur les 30 derniers jours.", "A local log of your reminders over the last 30 days."),
        ("Calendrier", "Calendar"),
        ("Retrouvez les échéances de vos comptes dans votre agenda.", "See your accounts’ due dates in your calendar."),
        ("Ouvrir les options Google Agenda…", "Open Google Calendar options…"),
        ("Ajout direct d’une échéance ou import groupé. Export compatible avec les autres agendas.", "Add a single due date directly or import them all at once. Export works with other calendars."),
        ("Assistants", "Assistants"),
        ("Pilotez le tracker depuis votre assistant de code.", "Control the tracker from your coding assistant."),
        ("Application", "App"),
        ("Démarrage, mises à jour et version installée.", "Startup, updates and installed version."),
        ("Démarrage", "Startup"),
        ("Démarrer avec Windows", "Start with Windows"),
        ("Section active", "Active section"),
        ("Recharger la section", "Reload section"),
        ("Relire la configuration actuelle. Les modifications non enregistrées de cette section seront abandonnées.", "Reread the current configuration. Unsaved changes in this section will be discarded."),

        // SettingsView · updates
        ("Mises à jour", "Updates"),
        ("Version installée", "Installed version"),
        ("Télécharger automatiquement les mises à jour", "Download updates automatically"),
        ("Recherche au démarrage puis toutes les 15 minutes sur GitHub. Le suivi continue pendant le téléchargement.", "Checks GitHub at startup, then every 15 minutes. Tracking continues during the download."),
        ("Installer au prochain démarrage du tracker", "Install the next time the tracker starts"),
        ("Installe une version déjà téléchargée et vérifiée. Aucune fermeture automatique pendant votre utilisation.", "Installs a version that’s already downloaded and verified. Never closes automatically while you’re using it."),
        ("Recevoir aussi les préversions", "Also receive pre-releases"),
        ("Désactivé : versions stables uniquement. Activez pour essayer les versions bêta avant leur validation complète.", "Off: stable versions only. Turn on to try beta versions before they’re fully validated."),
        ("Les mises à jour sont désactivées dans la démonstration.", "Updates are disabled in the demo."),
        ("Vérifiez les versions publiées sur le dépôt officiel.", "Check the versions published on the official repository."),
        ("Rechercher une mise à jour", "Check for updates"),
        ("Installer et relancer", "Install and restart"),
        ("Mettre à jour et relancer", "Update and restart"),
        ("Voir les versions sur GitHub ↗", "See releases on GitHub ↗"),
        ("Préversions incluses. Recherchez une mise à jour.", "Pre-releases included. Check for updates."),
        ("Versions stables uniquement. Recherchez une mise à jour.", "Stable versions only. Check for updates."),
        ("Recherche en cours…", "Checking for updates…"),
        ("Recherche annulée.", "Check cancelled."),
        ("Aucune version plus récente sur le canal {0}.", "No newer version on the {0} channel."),
        ("stable + préversions", "stable + pre-release"),
        ("stable", "stable"),
        ("Version {0} disponible.", "Version {0} available."),
        ("La version actuelle n’a pas été revérifiée.", "The current version wasn’t rechecked."),
        ("Version {0} connue dans le cache.", "Version {0} known from the cache."),
        ("Vérifié le {0:dd/MM/yyyy à HH:mm:ss}.", "Checked on {0:dd/MM/yyyy 'at' HH:mm:ss}."),
        ("Cache vérifié le {0:dd/MM/yyyy à HH:mm:ss}.", "Cache checked on {0:dd/MM/yyyy 'at' HH:mm:ss}."),
        ("Nouvelle vérification possible dès le {0:dd/MM/yyyy à HH:mm:ss}.", "Next check possible from {0:dd/MM/yyyy 'at' HH:mm:ss}."),
        ("Disponible à {0:HH:mm:ss}.", "Available at {0:HH:mm:ss}."),
        ("Recherche automatique désactivée.", "Automatic checking is off."),
        ("Recherche automatique indisponible dans cet exécutable.", "Automatic checking is unavailable in this executable."),
        ("Recherche automatique en pause.", "Automatic checking paused."),
        ("Téléchargement automatique en cours…", "Downloading automatically…"),
        ("Recherche automatique en cours…", "Checking automatically…"),
        ("Prochaine recherche automatique imminente.", "Next automatic check is imminent."),
        ("Prochaine recherche automatique : {0:dd/MM/yyyy à HH:mm:ss}.", "Next automatic check: {0:dd/MM/yyyy 'at' HH:mm:ss}."),
        ("Téléchargement et vérification de la mise à jour…", "Downloading and verifying the update…"),
        ("Installation annulée.", "Installation cancelled."),

        // SettingsView · diagnostics and dialogs
        ("Diagnostic", "Diagnostics"),
        ("Préparer un diagnostic…", "Prepare a diagnostic report…"),
        ("Aperçu avant copie. Aucun compte, quota, chemin personnel ni identifiant secret.", "Preview before copying. No accounts, quotas, personal paths or secret identifiers."),
        ("Quitter Codex Tracker", "Quit Codex Tracker"),
        ("Valider les réglages récupérés", "Confirm recovered settings"),
        ("Les réglages récupérés n’ont pas pu être enregistrés. Les fichiers existants sont conservés.", "The recovered settings couldn’t be saved. Existing files are kept."),
        ("Diagnostic à partager", "Diagnostic report to share"),
        ("Copier", "Copy"),
        ("Fermer", "Close"),
        ("Le presse-papiers est occupé. Réessayez dans quelques secondes.", "The clipboard is busy. Try again in a few seconds."),
        ("Action indisponible", "Action unavailable"),

        // ReminderSettingsView · rules
        ("Appel", "Call"),
        ("{0} j", "{0} d"),
        ("Le tracker doit rester ouvert et le PC éveillé. Chaque canal est indépendant ; un rappel passé ne confirme pas un reset dans Codex.",
            "The tracker must stay open and the PC awake. Each channel is independent; a past reminder doesn’t confirm a reset in Codex."),
        ("Désactivé", "Off"),
        ("Activer ces rappels", "Enable these reminders"),
        ("Tous les comptes, actuels et futurs", "All accounts, current and future"),
        ("Comptes concernés", "Accounts included"),
        ("SMS, appels et emails nécessitent un connecteur activé dans Canaux.", "SMS, calls and emails need a connector enabled in Channels."),
        ("Enregistrer ces rappels", "Save these reminders"),
        ("Règles modifiées ailleurs. Utilisez « Recharger la section » avant de réessayer.", "Rules changed elsewhere. Use “Reload section” before trying again."),
        ("Rappels enregistrés.", "Reminders saved."),
        ("Impossible d’enregistrer les rappels.", "Couldn’t save the reminders."),

        // ReminderSettingsView · channels
        ("Facultatif : utilisez vos propres comptes. Les envois partent directement de ce PC ; les frais sont facturés par votre prestataire.",
            "Optional: use your own accounts. Messages are sent directly from this PC; fees are billed by your provider."),
        ("Identifiants locaux illisibles. Aucun écrasement effectué.", "Local credentials are unreadable. Nothing was overwritten."),
        ("Activer Twilio", "Enable Twilio"),
        ("Expéditeur SMS (numéro ou identifiant autorisé)", "SMS sender (approved number or sender ID)"),
        ("Numéro Twilio autorisé pour les appels", "Twilio number approved for calls"),
        ("Votre numéro destinataire (+33…)", "Your recipient number (+44…)"),
        ("Vous pouvez configurer seulement les SMS ou seulement les appels. Les expéditeurs doivent être autorisés par Twilio pour votre destination.",
            "You can set up SMS only or calls only. Senders must be approved by Twilio for your destination."),
        ("Configuration enregistrée ; livraison non vérifiée.", "Configuration saved; delivery not verified."),
        ("Enregistrer Twilio", "Save Twilio"),
        ("Vérifiez les identifiants, le destinataire et au moins un expéditeur.", "Check the credentials, the recipient and at least one sender."),
        ("Configuration modifiée ailleurs. Utilisez « Recharger la section ».", "Configuration changed elsewhere. Use “Reload section”."),
        ("Enregistré localement et chiffré. Aucun envoi effectué.", "Saved locally and encrypted. Nothing was sent."),
        ("Impossible d’enregistrer les identifiants.", "Couldn’t save the credentials."),
        ("Envoyer un SMS de test · payant", "Send a test SMS · paid"),
        ("Recevoir un appel de test · payant", "Receive a test call · paid"),
        ("Supprimer les identifiants Twilio", "Delete Twilio credentials"),
        ("Identifiants supprimés ; canal désactivé.", "Credentials deleted; channel disabled."),
        ("Suppression impossible.", "Couldn’t delete."),
        ("Configurer Twilio ↗", "Set up Twilio ↗"),
        ("Twilio · SMS et appels", "Twilio · SMS and calls"),
        ("Activer SendGrid", "Enable SendGrid"),
        ("Clé API SendGrid · permission Mail Send", "SendGrid API key · Mail Send permission"),
        ("Adresse d’expéditeur vérifiée", "Verified sender address"),
        ("Adresse destinataire", "Recipient address"),
        ("SendGrid utilise une clé et une facturation distinctes de Twilio. Vérifiez votre expéditeur et les tarifs avant activation.",
            "SendGrid uses a key and billing separate from Twilio. Check your sender and pricing before enabling it."),
        ("Configuration enregistrée ; réception non vérifiée.", "Configuration saved; receipt not verified."),
        ("Enregistrer SendGrid", "Save SendGrid"),
        ("Vérifiez la clé et les deux adresses email.", "Check the key and both email addresses."),
        ("Envoyer un email de test", "Send a test email"),
        ("Supprimer la clé SendGrid", "Delete SendGrid key"),
        ("Vérifier l’expéditeur ↗", "Verify sender ↗"),
        ("Tarifs SendGrid ↗", "SendGrid pricing ↗"),
        ("Maximum de SMS par jour (0–100)", "Maximum SMS per day (0–100)"),
        ("Maximum d’appels par jour (0–20)", "Maximum calls per day (0–20)"),
        ("Heures silencieuses pour SMS et appels", "Quiet hours for SMS and calls"),
        ("Début (heure, 0–23)", "Start (hour, 0–23)"),
        ("Fin (heure, 0–23)", "End (hour, 0–23)"),
        ("Fuseau horaire", "Time zone"),
        ("Enregistrer les limites", "Save limits"),
        ("Vérifiez les limites, les heures et le fuseau.", "Check the limits, hours and time zone."),
        ("Limites modifiées ailleurs. Utilisez « Recharger la section ».", "Limits changed elsewhere. Use “Reload section”."),
        ("Limites enregistrées. Les tests téléphoniques les respectent aussi.", "Limits saved. Phone tests follow them too."),
        ("Enregistrement impossible.", "Couldn’t save."),
        ("Limites et heures silencieuses", "Limits and quiet hours"),

        // ReminderSettingsView · Windows test and history
        ("Tester une notification Windows", "Test a Windows notification"),
        ("Réglages Windows ↗", "Windows settings ↗"),
        ("Ouvrir les paramètres des notifications Windows", "Open Windows notification settings"),
        ("Vérification des notifications Windows…", "Checking Windows notifications…"),
        ("Test impossible ; consultez les réglages Windows et l’historique local.", "Test failed; check Windows settings and the local history."),
        ("Ouvrez Paramètres Windows → Système → Notifications.", "Open Windows Settings → System → Notifications."),
        ("Test impossible ; vérifiez la configuration et le journal local.", "Test failed; check the configuration and the local log."),
        ("Aucun rappel envoyé. Les événements des 30 derniers jours apparaîtront ici.", "No reminders sent. Events from the last 30 days will appear here."),
        ("estimation", "estimate"),
        ("Les notifications acceptées ne sont pas nécessairement lues ou livrées.", "Accepted notifications aren’t necessarily read or delivered."),
        ("Actualiser l’historique", "Refresh history"),

        // AssistantSettingsView
        ("Autoriser les assistants via MCP", "Allow assistants via MCP"),
        ("Comptes, quotas et rappels accessibles à votre assistant. Le tracker démarre en arrière-plan si nécessaire. Aucun serveur à héberger.",
            "Accounts, quotas and reminders available to your assistant. The tracker starts in the background if needed. No server to host."),
        ("Copier la configuration MCP", "Copy MCP configuration"),
        ("Ajoutez cette configuration à un client compatible MCP stdio. Les données demandées sont transmises à ce client et peuvent être traitées par son fournisseur d’IA.\n\nLes clés sont enregistrées en écriture seule. Une clé saisie via un assistant peut rester dans son contexte. Les tests externes et les nouveaux envois nécessitent votre confirmation ici.",
            "Add this configuration to an MCP stdio-compatible client. Requested data is sent to that client and may be processed by its AI provider.\n\nKeys are stored write-only. A key entered through an assistant may remain in its context. External tests and new sends require your confirmation here."),
        ("Désactivé · aucun accès aux données", "Off · no data access"),
        ("Activé · {0} connexion(s) locale(s)", "On · {0} local connection(s)"),
        ("Configuration copiée.", "Configuration copied."),
        ("Presse-papiers indisponible.", "Clipboard unavailable."),

        // TrackerControl · confirmation dialog
        ("Modifier les réglages généraux.", "Change general settings."),
        ("Limites : {0} SMS et {1} appels / jour.\nSilence : {2} ({3}).", "Limits: {0} SMS and {1} calls / day.\nQuiet hours: {2} ({3})."),
        ("désactivé", "off"),
        ("Remplacer les règles de rappel :", "Replace reminder rules:"),
        ("{0} · {1} min avant · {2} · {3}", "{0} · {1} min before · {2} · {3}"),
        ("tous les comptes", "all accounts"),
        ("Twilio · {0}\nSMS depuis {1}\nAppels depuis {2}\nDestinataire : {3}\nIdentifiants : masqués.", "Twilio · {0}\nSMS from {1}\nCalls from {2}\nRecipient: {3}\nCredentials: hidden."),
        ("activer / modifier", "enable / change"),
        ("désactiver", "disable"),
        ("SendGrid · {0}\nDe : {1}\nVers : {2}\nClé : masquée.", "SendGrid · {0}\nFrom: {1}\nTo: {2}\nKey: hidden."),
        ("Supprimer les identifiants {0}", "Delete {0} credentials"),
        ("Envoyer un test {0}. Les frais éventuels sont facturés par votre prestataire.", "Send a {0} test. Any fees are billed by your provider."),
        ("Message : test de rappel Codex Tracker. Les limites et heures silencieuses restent appliquées.", "Message: Codex Tracker reminder test. Limits and quiet hours still apply."),
        ("Destinataire SMS/appels : {0}\nDestinataire email : {1}", "SMS/call recipient: {0}\nEmail recipient: {1}"),
        ("Demande de l’assistant", "Assistant request"),
        ("Expire après cinq minutes. Aucun envoi avant votre confirmation.", "Expires after five minutes. Nothing is sent before you confirm."),
        ("Confirmer", "Confirm"),
        ("Annuler", "Cancel"),
        ("MCP suspendu : impossible de persister le résultat. Aucun nouvel envoi autorisé.", "MCP suspended: couldn’t persist the result. No new sends allowed."),
        ("MCP suspendu : journal local indisponible.", "MCP suspended: local log unavailable."),

        // ApplicationCommands
        ("Réglages invalides.", "Invalid settings."),
        ("Champs de connecteur manquants.", "Missing connector fields."),
        ("Champ de connecteur trop long.", "Connector field too long."),
        ("Configuration du canal incomplète.", "Incomplete channel configuration."),
        ("Le reset doit avoir eu lieu : choisissez une date et une heure passées.", "The reset must already have happened: choose a past date and time."),
        ("Règles invalides.", "Invalid rules."),
        ("Limites invalides.", "Invalid limits."),

        // PreferencesStore
        ("Des préférences locales étaient illisibles. Les réglages disponibles ont été récupérés avec les rappels, alertes et assistants désactivés. Vérifiez vos réglages avant de les réactiver. Le fichier d’origine est conservé.",
            "Some local preferences were unreadable. The available settings were recovered with reminders, alerts and assistants turned off. Review your settings before turning them back on. The original file is kept."),
        ("Compte masqué", "Hidden account"),
        ("Compte {0:00}", "Account {0:00}"),

        // SupportDiagnostics
        ("inconnue", "unknown"),
        ("démonstration", "demo"),
        ("Windows : {0} · {1}", "Windows: {0} · {1}"),
        ("Runtime .NET : {0}", ".NET runtime: {0}"),
        ("Mises à jour : {0}", "Updates: {0}"),
        ("stables + préversions", "stable + pre-releases"),
        ("stables", "stable"),
        ("Téléchargement auto : {0} · Installation au démarrage : {1}", "Auto download: {0} · Install at startup: {1}"),
        ("Mise à jour prête : {0}", "Update ready: {0}"),
        ("Préférences à vérifier : {0}", "Preferences to review: {0}"),
        ("Moteur de rappels disponible : {0}", "Reminder engine available: {0}"),
        ("État de notification Windows : {0} (ne détermine pas tous les réglages Ne pas déranger)", "Windows notification state: {0} (doesn’t cover every Do Not Disturb setting)"),
        ("MCP activé : {0} · Disponible : {1}", "MCP enabled: {0} · Available: {1}"),
        ("Emplacement Codex : {0}", "Codex location: {0}"),
        ("Session : {0} · App-server : {1}", "Session: {0} · App-server: {1}"),
        ("Dernier diagnostic : {0}", "Last diagnostic: {0}"),
        ("Vérification : {0}", "Checked: {0}"),
        ("Dernier relevé réussi : {0}", "Last successful reading: {0}"),
        ("Compatibilité Codex : non vérifiée dans cette instance.", "Codex compatibility: not checked in this instance."),
        ("oui", "yes"),
        ("non", "no"),
    ];
}
