namespace CodexTracker.Core;

/// <summary>English text for Core and Codex messages, keyed by the exact French source text or template.</summary>
internal static class EnglishCore
{
    internal static readonly (string French, string English)[] Entries =
    [
        // Account advice
        ("Le compte actuellement ouvert dans Codex n’est pas identifié avec certitude.", "The account currently open in Codex cannot be identified with certainty."),
        ("Un reset Codex a été déclaré. Un nouveau relevé mesuré est nécessaire avant de conseiller un autre compte.", "A Codex reset was declared. A new measured reading is needed before suggesting another account."),
        ("Compte actuel confortable", "Current account is comfortable"),
        ("Les quotas de 5 heures et de la semaine dépassent 20 % dans le relevé du {0}.", "The 5-hour and weekly quotas are above 20% in the reading from {0}."),
        ("Un quota du compte actuel est à 20 % ou moins. Aucun autre relevé assez récent, complet et sans reset atteint ne permet de suggérer un compte à vérifier.", "A quota on the current account is at 20% or less. No other recent, complete reading without a passed reset can suggest an account to check."),
        ("À vérifier dans Codex", "Check in Codex"),
        ("Un quota du compte actuel est à 20 % ou moins. Au dernier relevé du {0}, ce compte avait plus de 20 % sur les deux fenêtres. Ses quotas actuels restent à vérifier dans Codex ; les capacités des offres ne sont pas comparées.", "A quota on the current account is at 20% or less. At its last reading on {0}, this account had more than 20% in both windows. Check its current quotas in Codex; plan capacities are not compared."),
        ("Un relevé complet et récent du compte actuel est nécessaire avant de proposer un autre compte.", "A complete, recent reading of the current account is needed before suggesting another account."),
        ("La session ou le dernier relevé du compte actuel doit être vérifié dans Codex.", "Check the session or the last reading of the current account in Codex."),
        ("La lecture du compte actuel est en cours. Le conseil attend son résultat.", "The current account is being read. The advice waits for the result."),
        ("Le dernier relevé du compte actuel est trop ancien ou sa date est incohérente. Actualisez les quotas avant de choisir.", "The last reading of the current account is too old or its date is inconsistent. Refresh quotas before choosing."),
        ("Les deux quotas, de 5 heures et de la semaine, et leurs dates de reset doivent être connus pour donner un conseil.", "Both the 5-hour and weekly quotas, and their reset dates, must be known to give advice."),
        ("Une date de reset est atteinte. Un nouveau relevé doit confirmer les quotas ; aucun rechargement n’est supposé.", "A reset date has passed. A new reading must confirm the quotas; no refill is assumed."),
        ("Conseil indisponible", "Advice unavailable"),

        // Calendar export
        ("Date prévue selon le relevé du {0:dd/MM/yyyy HH:mm:ss zzz}. Export ponctuel : les modifications ultérieures ne sont pas synchronisées. Vérifiez dans {1}.", "Expected date based on the reading from {0:dd/MM/yyyy HH:mm:ss zzz}. One-off export: later changes are not synced. Check in {1}."),
        ("Reset {0} · semaine", "{0} weekly reset"),
        ("Reset {0} · 5 heures", "{0} 5-hour reset"),
        ("Expiration d’un reset en réserve", "Reset credit expiry"),

        // Reminders and notifications
        ("Reset hebdomadaire", "Weekly reset"),
        ("Reset 5 heures", "5-hour reset"),
        ("Expiration de réserve", "Credit expiry"),
        ("Un reset en réserve va expirer", "A reserve reset is about to expire"),
        ("Ouvrir le compte dans Codex Tracker : {0}", "Open the account in Codex Tracker: {0}"),
        ("{0} · expire le {1:dd/MM/yyyy HH:mm zzz}.\nUtilisez-le dans {2} avant cette date pour ne pas le perdre.\nRelevé : {3:dd/MM/yyyy HH:mm zzz}.", "{0} · expires on {1:dd/MM/yyyy HH:mm zzz}.\nUse it in {2} before then so it is not lost.\nReading: {3:dd/MM/yyyy HH:mm zzz}."),
        ("Reset général annoncé comme terminé", "Global reset announced as complete"),
        ("Compte probablement rechargé", "Account probably refilled"),
        ("{0} · Semaine probablement à 100 %.\nConfirmation publique du {1:dd/MM/yyyy HH:mm:ss zzz}.\nDernier relevé : {2:dd/MM/yyyy HH:mm:ss zzz}. À confirmer dans {3} ; source dans Resets.", "{0} · Weekly quota probably at 100%.\nPublicly confirmed on {1:dd/MM/yyyy HH:mm:ss zzz}.\nLast reading: {2:dd/MM/yyyy HH:mm:ss zzz}. Confirm in {3}; source in Resets."),
        ("{0} · 5 heures probablement à 100 %.\nConfirmation publique du {1:dd/MM/yyyy HH:mm:ss zzz}.\nDernier relevé : {2:dd/MM/yyyy HH:mm:ss zzz}. À confirmer dans {3} ; source dans Resets.", "{0} · 5-hour quota probably at 100%.\nPublicly confirmed on {1:dd/MM/yyyy HH:mm:ss zzz}.\nLast reading: {2:dd/MM/yyyy HH:mm:ss zzz}. Confirm in {3}; source in Resets."),
        ("{0} · Semaine probablement à 100 %.\nReset prévu le {1:dd/MM/yyyy HH:mm:ss zzz}.\nDernier relevé : {2:dd/MM/yyyy HH:mm:ss zzz}. À confirmer dans {3}.", "{0} · Weekly quota probably at 100%.\nReset expected on {1:dd/MM/yyyy HH:mm:ss zzz}.\nLast reading: {2:dd/MM/yyyy HH:mm:ss zzz}. Confirm in {3}."),
        ("{0} · 5 heures probablement à 100 %.\nReset prévu le {1:dd/MM/yyyy HH:mm:ss zzz}.\nDernier relevé : {2:dd/MM/yyyy HH:mm:ss zzz}. À confirmer dans {3}.", "{0} · 5-hour quota probably at 100%.\nReset expected on {1:dd/MM/yyyy HH:mm:ss zzz}.\nLast reading: {2:dd/MM/yyyy HH:mm:ss zzz}. Confirm in {3}."),
        ("{0} · {1}\nÉchéance : {2:dd/MM/yyyy HH:mm:ss zzz}\nRelevé : {3:dd/MM/yyyy HH:mm:ss zzz}\nÀ confirmer dans {4}.", "{0} · {1}\nDue: {2:dd/MM/yyyy HH:mm:ss zzz}\nReading: {3:dd/MM/yyyy HH:mm:ss zzz}\nConfirm in {4}."),
        ("{0} événements de quota", "{0} quota events"),
        ("1 autre(s) événement(s) dans l’onglet Resets.", "1 other event in the Resets tab."),
        ("{0} autre(s) événement(s) dans l’onglet Resets.", "{0} other events in the Resets tab."),
        ("Reset général · 1 compte à vérifier", "Global reset · 1 account to check"),
        ("Reset général · {0} comptes à vérifier", "Global reset · {0} accounts to check"),
        ("{0}\nQuota probablement rechargé, à confirmer dans Codex.\nAnnonce du {1:dd/MM/yyyy HH:mm:ss zzz}. Sources et relevés datés dans Resets.", "{0}\nQuota probably refilled; confirm in Codex.\nAnnounced on {1:dd/MM/yyyy HH:mm:ss zzz}. Sources and dated readings in Resets."),
        ("D’autres rappels sont disponibles dans Resets.", "More reminders are available in Resets."),

        // Usage forecast
        ("L'estimation apparaîtra après au moins 15 minutes de suivi continu.", "The estimate will appear after at least 15 minutes of continuous tracking."),
        ("Le dernier relevé est trop ancien pour estimer la consommation actuelle.", "The last reading is too old to estimate current usage."),
        ("Les informations du quota hebdomadaire sont insuffisantes.", "Not enough information about the weekly quota."),
        ("Les informations du quota de 5 heures sont insuffisantes.", "Not enough information about the 5-hour quota."),
        ("En attente d'un relevé confirmant la nouvelle période de quota.", "Waiting for a reading that confirms the new quota period."),
        ("Il faut au moins 15 minutes de suivi continu dans la même période de quota.", "At least 15 minutes of continuous tracking within the same quota period are needed."),
        ("Aucune consommation régulière mesurable sur cette période.", "No measurable steady usage in this period."),
        ("Le rythme de consommation est trop irrégulier pour une estimation fiable.", "Usage is too irregular for a reliable estimate."),
        ("Au rythme observé, le reset du quota hebdomadaire devrait précéder son épuisement.", "At the observed pace, the weekly reset should come before the quota runs out."),
        ("Au rythme observé, le reset du quota de 5 heures devrait précéder son épuisement.", "At the observed pace, the 5-hour reset should come before the quota runs out."),
        ("Estimation du quota hebdomadaire, si le rythme observé reste comparable.", "Weekly quota estimate, if the observed pace stays similar."),
        ("Estimation du quota de 5 heures, si le rythme observé reste comparable.", "5-hour quota estimate, if the observed pace stays similar."),
        ("Ouvrez ce compte dans {0} pour estimer sa consommation actuelle.", "Open this account in {0} to estimate its current usage."),
        ("L'estimation est suspendue jusqu'au prochain relevé disponible.", "The estimate is paused until the next available reading."),
        ("Un reset Codex a été déclaré. L’estimation reprendra après un nouveau relevé mesuré.", "A Codex reset was declared. The estimate resumes after a new measured reading."),

        // Codex service and session
        ("Détection du compte Codex…", "Detecting the Codex account…"),
        ("Compte Codex détecté · lecture des quotas…", "Codex account detected · reading quotas…"),
        ("Actualisation du compte ouvert dans Codex…", "Refreshing the account open in Codex…"),
        ("À jour · changements de compte détectés automatiquement", "Up to date · account changes detected automatically"),
        ("Suivi en pause pendant la veille", "Tracking paused during sleep"),
        ("Sortie de veille · vérification du compte Codex…", "Resumed from sleep · checking the Codex account…"),
        ("Le tracker n'est pas encore prêt.", "The tracker is not ready yet."),
        ("Le compte actif est suivi automatiquement. Changez de compte dans {0} avant de le retirer.", "The active account is tracked automatically. Switch accounts in {0} before removing it."),
        ("Codex a retourné un autre compte. Le relevé a été ignoré.", "Codex returned a different account. The reading was ignored."),
        ("Codex met trop de temps à répondre. Dernier relevé conservé.", "Codex is taking too long to respond. Last reading kept."),
        ("Un relevé plus ancien a été ignoré. Les dernières données sont conservées.", "An older reading was ignored. The latest data is kept."),
        ("Les données ne sont pas disponibles. Dernier relevé conservé ; réessayez depuis Codex.", "Data is unavailable. Last reading kept; try again from Codex."),
        ("Aucune session locale détectée. Ouvrez Codex et connectez-vous avec votre compte ChatGPT.", "No local session detected. Open Codex and sign in with your ChatGPT account."),
        ("La session Codex est momentanément illisible. Fermez puis rouvrez Codex et actualisez le tracker.", "The Codex session is temporarily unreadable. Close and reopen Codex, then refresh the tracker."),
        ("Le dossier CODEX_HOME est invalide. Corrigez cette variable puis relancez le tracker.", "The CODEX_HOME folder is invalid. Fix this variable, then restart the tracker."),
        ("Le format de la session n'est pas pris en charge. Mettez à jour Codex et connectez-vous avec votre compte ChatGPT ; une clé API seule ne permet pas de suivre ces quotas.", "This session format is not supported. Update Codex and sign in with your ChatGPT account; an API key alone cannot track these quotas."),
        ("Impossible de démarrer le service Codex.", "Could not start the Codex service."),
        ("Codex Tracker accepte uniquement la session déjà ouverte dans Codex.", "Codex Tracker only accepts the session already open in Codex."),
        ("Cette opération ne fait pas partie du suivi en lecture seule.", "This operation is not part of read-only tracking."),
        ("La réponse Codex dépasse la taille autorisée.", "The Codex response exceeds the allowed size."),
        ("Réponse Codex incompatible. Mettez à jour Codex et le tracker.", "Incompatible Codex response. Update Codex and the tracker."),
        ("Le service Codex s'est arrêté. Actualisez pour réessayer.", "The Codex service stopped. Refresh to try again."),
        ("Cette version de Codex ne prend pas en charge la lecture des quotas. Mettez à jour Codex et le tracker.", "This version of Codex cannot read quotas. Update Codex and the tracker."),
        ("Codex n'a pas pu répondre (RPC {0}). Actualisez ou vérifiez ce compte dans Codex.", "Codex could not respond (RPC {0}). Refresh or check this account in Codex."),
        ("Le service Codex n'a pas quitté à temps. Redémarrez le tracker avant une nouvelle connexion.", "The Codex service did not exit in time. Restart the tracker before connecting again."),
        ("Le service Codex est introuvable. Installez ou mettez à jour Codex, puis relancez le tracker.", "The Codex service was not found. Install or update Codex, then restart the tracker."),
        ("Windows ne peut pas démarrer le service Codex (erreur {0}). Ouvrez ou mettez à jour Codex, puis actualisez les quotas. Dernier relevé conservé.", "Windows cannot start the Codex service (error {0}). Open or update Codex, then refresh quotas. Last reading kept."),
        ("Cette session ne contient pas de connexion ChatGPT gérée par Codex. Connectez-vous dans Codex avec votre compte ChatGPT.", "This session has no ChatGPT sign-in managed by Codex. Sign in to Codex with your ChatGPT account."),
        ("La session Codex est incomplète. Ouvrez ce compte dans Codex pour l'actualiser.", "The Codex session is incomplete. Open this account in Codex to refresh it."),
        ("L'identité de cette session est indisponible. Ouvrez ce compte dans Codex pour l'actualiser.", "This session’s identity is unavailable. Open this account in Codex to refresh it."),
        ("Le format de la session Codex n'est pas pris en charge.", "The Codex session format is not supported."),
        ("Codex n'a pas confirmé le compte actif. Ouvrez ce compte dans Codex puis actualisez.", "Codex did not confirm the active account. Open this account in Codex, then refresh."),
        ("Le relevé appartient à un autre compte. Il a été ignoré.", "The reading belongs to another account and was ignored."),
        ("Le compte a changé dans Codex. Le relevé précédent a été ignoré.", "The account changed in Codex. The previous reading was ignored."),
        ("La session a expiré. Ouvrez Codex pour qu'il renouvelle sa connexion, puis actualisez le tracker.", "The session has expired. Open Codex so it can renew its sign-in, then refresh the tracker."),
        ("Le fichier de session Codex est incompatible. Ouvrez votre compte dans Codex puis actualisez.", "The Codex session file is incompatible. Open your account in Codex, then refresh."),

        // Claude Code
        ("Compte Claude Code détecté · lecture des relevés locaux…", "Claude Code account detected · reading local quotas…"),
        ("Lecture des relevés Claude Code…", "Reading Claude Code quotas…"),
        ("À jour · comptes Codex et Claude Code suivis automatiquement", "Up to date · Codex and Claude Code accounts tracked automatically"),
        ("Aucune session locale Claude Code détectée. Ouvrez Claude Code et connectez-vous.", "No local Claude Code session detected. Open Claude Code and sign in."),
        ("La session locale Claude Code est illisible. Derniers comptes et relevés conservés ; vérifiez votre connexion dans Claude Code.", "The local Claude Code session is unreadable. Latest accounts and readings kept; check your sign-in in Claude Code."),
        ("Claude Code a retourné un autre compte ou un relevé invalide. Les données ont été ignorées.", "Claude Code returned a different account or an invalid reading. The data was ignored."),
        ("Le relevé Claude Code met trop de temps à répondre. Dernier relevé conservé.", "The Claude Code reading is taking too long. Last reading kept."),
        ("Le relevé Claude Code est indisponible. Les dernières données sont conservées.", "The Claude Code reading is unavailable. The latest data is kept."),
        ("Un relevé Claude Code plus ancien a été ignoré. Les dernières données sont conservées.", "An older Claude Code reading was ignored. The latest data is kept."),
        ("Le dossier CLAUDE_CONFIG_DIR est invalide. Corrigez cette variable puis relancez le tracker.", "The CLAUDE_CONFIG_DIR folder is invalid. Fix this variable, then restart the tracker."),
        ("Aucune identité Claude locale détectée. Ouvrez l’onglet Code de l’application Claude ou connectez-vous dans le terminal.", "No local Claude identity detected. Open the Code tab in the Claude app or sign in from the terminal."),
        ("L’identité locale Claude Code est incomplète. Ouvrez Claude Code et vérifiez votre connexion.", "The local Claude Code identity is incomplete. Open Claude Code and check your sign-in."),
        ("Personnel", "Personal"),
        ("Équipe", "Team"),
        ("Entreprise", "Enterprise"),
        ("La session Claude Code a expiré. Ouvrez Claude Code pour renouveler votre connexion ; le dernier relevé est conservé.", "The Claude Code session has expired. Open Claude Code to renew your sign-in; the last reading is kept."),
        ("Quotas Claude Code en attente. Activez les relevés dans Réglages → Général, puis utilisez Claude Code.", "Claude Code quotas pending. Turn on readings in Settings → General, then use Claude Code."),
        ("Le compte Claude Code a changé. Le relevé a été ignoré.", "The Claude Code account changed. The reading was ignored."),
        ("Quotas Claude en attente. Ouvrez l’application Claude pour un relevé automatique, ou configurez les relevés du terminal dans Réglages → Général.", "Claude quotas pending. Open the Claude app for an automatic reading, or set up terminal readings in Settings → General."),
        ("Claude Code · 5 h : {0} · semaine : {1}", "Claude Code · 5h: {0} · week: {1}"),
        ("{0:0}% restant", "{0:0}% left"),

        // Global reset sources
        ("Source non vérifiable · estimations retirées.", "Source cannot be verified · estimates removed."),
        ("Source temporairement limitée · nouvel essai dans 30 min.", "Source temporarily rate-limited · retrying in 30 min."),
        ("Vérification impossible pour le moment.", "Unable to check right now."),
        ("Sources indisponibles · dernier contrôle réussi conservé.", "Sources unavailable · last successful check kept."),

        // Local storage
        ("Codex Tracker est déjà ouvert. Fermez l'autre instance avant de continuer.", "Codex Tracker is already open. Close the other instance before continuing."),
        ("Les comptes ont été récupérés depuis la dernière sauvegarde locale valide. Le fichier d’origine est conservé.", "Accounts were recovered from the last valid local backup. The original file is kept."),
        ("La liste des comptes et sa sauvegarde sont illisibles. Vos fichiers sont conservés ; aucune réinitialisation automatique n’a été effectuée. Restaurez une sauvegarde locale valide avant de relancer le tracker.", "The account list and its backup are unreadable. Your files are kept; nothing was reset automatically. Restore a valid local backup before restarting the tracker."),
        ("Les derniers relevés ont été récupérés depuis la sauvegarde locale. Leurs dates d’observation restent inchangées.", "The latest readings were recovered from the local backup. Their observation dates are unchanged."),
        ("Les relevés locaux sont illisibles. Ils restent conservés ; seul le compte ouvert dans Codex peut être actualisé.", "Local readings are unreadable. They are kept; only the account open in Codex can be refreshed."),
        ("L'identité Windows est indisponible.", "The Windows identity is unavailable."),
        ("Le journal de récupération est illisible. Vos comptes sont conservés ; aucune nouvelle fusion automatique n’a été tentée.", "The recovery log is unreadable. Your accounts are kept; no new automatic merge was attempted."),
        ("Les comptes et relevés d’un ancien stockage Windows ont été réunis. Une copie des données d’origine est conservée localement.", "Accounts and readings from an old Windows storage location were merged. A copy of the original data is kept locally."),
        ("Le bureau Windows n’est pas disponible. Lancez le tracker depuis le menu Démarrer.", "The Windows desktop is not available. Start the tracker from the Start menu."),

        // Reminder delivery
        ("Échéance dépassée, règle désactivée ou événement modifié.", "Due date passed, rule turned off or event changed."),
        ("Rappel déjà envoyé avant migration.", "Reminder already sent before migration."),
        ("Rappel remplacé par le délai le plus proche.", "Reminder replaced by the nearest lead time."),
        ("En attente d’une nouvelle vérification des sources publiques.", "Waiting for public sources to be checked again."),
        ("Canal désactivé ou configuration incomplète.", "Channel turned off or configuration incomplete."),
        ("Heures silencieuses.", "Quiet hours."),
        ("Limite quotidienne atteinte.", "Daily limit reached."),
        ("Envoi en cours.", "Sending."),
        ("Transmission à Windows.", "Handing over to Windows."),
        ("Rappels suspendus : impossible de lire ou d’enregistrer les données locales.", "Reminders paused: local data cannot be read or saved."),
        ("Notification Windows impossible. Vérifiez les réglages de notification Windows.", "Windows notification failed. Check the Windows notification settings."),
        ("Configuration modifiée pendant l’attente ; test annulé.", "Configuration changed while waiting; test cancelled."),
        ("Enregistrez et activez d’abord le connecteur.", "Save and turn on the connector first."),
        ("Test bloqué par les heures silencieuses ou la limite quotidienne.", "Test blocked by quiet hours or the daily limit."),
        ("Test de notification", "Notification test"),
        ("Test demandé manuellement.", "Test requested manually."),
        ("Envoi interrompu : résultat inconnu, aucune réémission automatique.", "Sending interrupted: result unknown, no automatic resend."),
        ("Prestataire : HTTP {0}. Aucune réémission automatique.", "Provider: HTTP {0}. No automatic resend."),
        ("Accepté par SendGrid ; réception non confirmée.", "Accepted by SendGrid; delivery not confirmed."),
        ("Réponse du prestataire non reconnue.", "Unrecognised provider response."),
        ("Accepté par Twilio ; suivi en cours.", "Accepted by Twilio; tracking delivery."),
        ("Résultat inconnu après interruption réseau ; aucune réémission automatique.", "Result unknown after a network interruption; no automatic resend."),
        ("SMS livré selon Twilio.", "SMS delivered according to Twilio."),
        ("Appel terminé ; écoute non confirmée.", "Call completed; not confirmed as heard."),
        ("Twilio : {0}", "Twilio: {0}"),
        // Spoken by Twilio in the interface language; the date formats follow Loc.Culture.
        ("Codex Tracker. {0}. {1} prévu le {2:dd MMMM à HH:mm}. Relevé du {3:dd MMMM à HH:mm}. Vérifiez votre compte dans Codex.", "Codex Tracker. {0}. {1} due on {2:d MMMM 'at' HH:mm}. Reading from {3:d MMMM 'at' HH:mm}. Check your account in Codex."),
        // SMS text stays ASCII so a message fits in one GSM-7 segment.
        ("Reset semaine", "Weekly reset"),
        ("Reset 5h", "5h reset"),
        ("Expiration reserve", "Credit expiry"),
        ("Codex {0}: {1} le {2:dd/MM HH:mm zzz}. Releve {3:dd/MM HH:mm zzz}. Verifiez dans Codex.", "Codex {0}: {1} on {2:dd/MM HH:mm zzz}. Reading {3:dd/MM HH:mm zzz}. Check in Codex."),
    ];
}
